services:
  - type: web
    name: api-smart-store
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: API_KEY
        sync: false

      - key: SAAS_API_URL
        value: https://api-fluxoclean.onrender.com/api

      - key: SMARTSTORE
        value: https://smart-store.fluxoclean.com.br

      - key: FLUXOCLEAN
        value: https://fluxoclean.com.br

    autoDeploy: false
